  <header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-7 py-4">
            <h4>About</h4>
            <p class="text-body-secondary">
              I am currently a 4th year student at the University of North Carolina at Greensboro. I am almost finished
              with my bachelors in Computer Science! I have found interests in concepts like Web Development, AI
              workflows/prompting, and Software Engineering through my education. My goal is to start my career in one
              of these interests, and eventually get into Game Development and Design.
            </p>
          </div>
          <div class="col-sm-4 offset-md-1 py-4">
            <h4>Contact</h4>
            <ul class="list-unstyled">
              <li><a href="https://www.linkedin.com/in/cameron-rackley-131a20303/" class="text-white">linkedin</a></li>
              <li>
                <a href="#" class="text-white" data-bs-toggle="modal"
                  data-bs-target="#resumeModal">My Resume</a>
              </li>
              <li>Email me: cameronrackley2023@outlook.com</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
          <strong>Cameron Rackley's Portfolio</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
          aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
  </header>
